# Generated by Django 4.2.6 on 2023-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='lunch_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
