# Generated by Django 4.2.6 on 2023-10-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_timerecord_lunch_time_alter_timerecord_time_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='timerecord',
            options={'verbose_name': 'Time Record', 'verbose_name_plural': 'Time Records'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='employee_app.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='lunch_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Lunch Time'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Out'),
        ),
        migrations.AlterUniqueTogether(
            name='timerecord',
            unique_together={('employee', 'date')},
        ),
    ]
